name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: my_db
        options: --health-cmd="pg_isready -U postgres" --health-timeout=30s --health-retries=3

    steps:
    - uses: actions/checkout@v4
    
    - name: Set DATABASE_URL for PostgreSQL
      run: echo "DATABASE_URL=postgres://postgres:password@localhost:5432/my_db" >> $GITHUB_ENV
    - name: Install dependencies
      run: cargo install sqlx-cli
    - name: Prepare sqlx cache
      run: cargo sqlx prepare
    - name: Run fmt
      run: cargo fmt --all -- --check --verbose
    - name: Run Clippy
      run: cargo clippy -- -D warnings --verbose
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
